openapi: 3.0.1
info:
  title: Estadísticas iHelemet
  description: Estadísticas iHelemt
  contact:
    name: Soporte iHelmet
    email: contacto@ihelmet.com
  version: "1.0"
servers:
- url: /
paths:
  /falls/{id}:
    get:
      tags:
      - global
      summary: obtiene el número de caídas de un usuario en el último mes.
      description: obtiene el número de caídas de un usuario en el último mes.
      operationId: getFalls
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /kms/{id}:
    get:
      tags:
      - global
      summary: obtiene el número de kilómetros recorridos por un usuario en el último
        mes.
      description: obtiene el número de kilómetros recorridos por un usuario en el
        último mes.
      operationId: obtinfokms
      parameters:
      - name: id
        in: path
        description: id del dispositivo
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /time/{id}:
    get:
      tags:
      - global
      summary: obtiene las horas de uso por un usuario en el último mes.
      description: obtiene las horas de uso por un usuario en el último mes.
      operationId: obtinfotime
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /sos/{id}:
    get:
      tags:
      - global
      summary: número de llamadas a emergencias en el último mes causadas por la caída
        de un usuario.
      description: número de llamadas a emergencias en el último mes causadas por
        la caída de un usuario.
      operationId: obtinfosos
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /score/{id}:
    get:
      tags:
      - global
      summary: obtiene la puntuación de un usuario. Métrica obtenida en función del
        número de kilómetros recorridos y los accidentes involucrados en un mes.
      description: obtiene la puntuación de un usuario. Métrica obtenida en función
        del número de kilómetros recorridos y los accidentes involucrados en un mes.
      operationId: obtinfoscore
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /commonlocations/{id}:
    get:
      tags:
      - global
      summary: obtiene las ubicaciones frecuentes de un usuario.
      description: obtiene las ubicaciones frecuentes de un usuario.
      operationId: obtinfolocations
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /avgspeed/{id}:
    get:
      tags:
      - global
      summary: obtiene la velocidad media de un usuario en el último mes.
      description: obtiene la velocidad media de un usuario en el último mes.
      operationId: obtinfoavgspeed
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
  /maxspeed/{id}:
    get:
      tags:
      - global
      summary: obtiene la velocidad máxima de un usuario en el último mes.
      description: obtiene la velocidad máxima de un usuario en el último mes.
      operationId: obtinfomaxspeed
      parameters:
      - name: id
        in: path
        description: id del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: Random number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Value'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Endpoint not found
                type: string
                example: Not found
                x-content-type: text/plain
      x-swagger-router-controller: Global
components:
  schemas:
    Value:
      type: object
      properties:
        value:
          maximum: 999999
          minimum: 1
          type: integer
      example:
        value: 10120
    ValueBool:
      type: object
      properties:
        value:
          type: boolean
      example:
        value: true
  responses:
    successful_random_number:
      description: Random number
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Value'
    successful_bool:
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValueBool'
    "404NotFound":
      description: Not found response
      content:
        text/plain:
          schema:
            title: Endpoint not found
            type: string
            example: Not found
            x-content-type: text/plain
